name: Build and Deploy to Azure Functions

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'func-dietanalysis-lp-dev'
  PYTHON_VERSION: '3.10'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        # Switch to remote build. This tells Azure to handle the 
        # installation of bcrypt/pandas on their end, bypassing Kudu config steps.
        scm-do-build-during-deployment: true
        enable-oryx-build: true
        remote-build: true
